name: Build my nextjs app
 
on:
 push:
  branches: [main]

jobs:
  build-nextJs-app:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v6.0.0
    - name: Setup Node Js
    - uses: actions/setup-node@v6.0.0
      with:
       node version: 22.x
    - name: install-Dependency
      run: npm install
    - name: build nextJs app
      run: npm run build
